[theme]
base = "dark"
primaryColor = "#FE2C55"
backgroundColor = "#0E0E10"
secondaryBackgroundColor = "#1A1A1E"
textColor = "#FAFAFA"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
